---
theme: jekyll-theme-merlot
title: Nieuw hefdak op een Kip Kompakt
description: Een verslag van het vervangen van het tentdoek van een Kip Kompakt met hefdak
show_downloads: false
google_analytics: G-RQ34S398CP
