---
name: check-doc

# Triggers the workflow on push or pull request events
on: [push, pull_request] # yamllint disable-line

jobs:
  test-doc:
    runs-on: ubuntu-latest
    name: Test documentation
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: lint markdown file
        uses: nosborn/github-action-markdown-cli@v2.0.0
        with:
          files: .

      - name: Lint yaml files
        uses: ibiqlik/action-yamllint@v3
